import type { System } from "@/components/SystemCard";

export type DetailedSystem = System & { problem: string; constraints: string[]; approach: string; decisions: { title: string; body: string }[]; failures: string; result: string; next: string; architecture: string[] };

export const systems: DetailedSystem[] = [
  { slug: "mx-sentinel", number: "01", title: "MX Sentinel", eyebrow: "AI-powered email infrastructure observability", description: "A production operations layer that helps mail operators understand why delivery is failing — before the incident becomes a support queue.", summary: "Correlates SMTP telemetry, DNS changes, DMARC data, reputation signals, and incidents. Deterministic evidence comes first; AI assists with diagnosis.", tags: ["Go", "Event-driven", "Observability", "AI diagnostics"], nodes: ["Telemetry", "Event bus", "Correlation", "Operator"], problem: "Email failures are noisy. Operators were forced to assemble a story from mail logs, DNS records, aggregate reports, and customer tickets while delivery was already degraded.", constraints: ["High-volume telemetry with privacy boundaries", "External DNS and provider signals can be incomplete", "A diagnosis must be explainable enough to act on"], approach: "A Go-based event system collects metadata, validates mail configuration, and correlates changes and delivery signals into operational incidents. An AI layer writes a readable hypothesis and remediation path from that evidence; it is not the source of truth.", architecture: ["Postfix & DNS", "Go collectors", "NATS events", "PostgreSQL / ClickHouse", "Incident dashboard"], decisions: [{ title: "Evidence before narrative", body: "The correlation engine creates the incident record. AI summarizes the evidence rather than inventing a conclusion." }, { title: "Separate stores for separate work", body: "PostgreSQL carries operational state, ClickHouse serves telemetry analysis, and Redis supports low-latency coordination." }, { title: "Metadata-only diagnostics", body: "The system avoids email bodies and hashes sensitive recipient data." }], failures: "Collectors spool safely when a bus is unavailable. Jobs are idempotent, retries are visible, and operators can distinguish an infrastructure outage from missing evidence.", result: "A single operational surface for moving from delivery symptom to likely cause, with the signals preserved for review.", next: "Add richer long-term baselines and more provider-specific feedback loops." },
  { slug: "vas", number: "02", title: "Video Automation Service (VAS)", eyebrow: "AI video production engine", description: "A system that turns a topic or script into a finished video through an AI editorial layer and a deterministic rendering pipeline.", summary: "AI plans. Deterministic systems execute. Structured edit plans, workers, provider fallbacks, asset reuse, cost controls, and recovery make the pipeline operable.", tags: ["FastAPI", "Remotion", "FFmpeg", "Worker architecture"], nodes: ["Brief", "Edit plan", "Workers", "Render", "Delivery"], problem: "Video generation becomes unreliable when creative choices, media assets, rendering, and external providers are mixed into one opaque request.", constraints: ["Slow and failure-prone external providers", "Expensive rendering", "Partial reruns should not repeat completed work", "Editorial output needs structure"], approach: "AI produces a typed editorial and edit-plan contract. A FastAPI control plane and workers resolve assets, render deterministic scenes with Remotion and FFmpeg, and retain the state needed to resume safely.", architecture: ["Brief / script", "FastAPI control plane", "Queue workers", "Assets & cache", "Remotion / FFmpeg"], decisions: [{ title: "Plan as a contract", body: "A structured edit plan separates editorial reasoning from rendering execution." }, { title: "Cache at the asset boundary", body: "Completed clips and assets can be reused, avoiding an expensive full regeneration after a small edit." }, { title: "Fallbacks are explicit", body: "Provider routing is a system decision with cost and capability boundaries, not a hidden prompt trick." }], failures: "Jobs persist their stage and outputs. Workers retry safe actions, provider fallbacks can be selected, and failed rendering stays recoverable rather than becoming a blank final result.", result: "A production-scale implementation with substantial automated coverage and multiple provider integrations, built to make a complex pipeline observable.", next: "Move more rendering capacity to remote workers while preserving the same recovery model." },
];

export const getSystem = (slug: string) => systems.find(system => system.slug === slug);
